### ISSUE TITLE
Syncing Past Events in Outlook Calendar with Google Calendar

### ISSUE THREAD

**Issue by Tosko4** [MShekow/ng-outlook-google-calendar-sync#11]
First of all, thank you for creating this NG flow and the deprecated 0.9 previous version. Currently I am still on the old version and need to migrate to NG soon. 

It’s been incredibly helpful for syncing my Outlook and Google calendars! I’ve been using your solution, but I’ve encountered a challenge that’s been impacting my workflow.

I rely on timeboxing to manage my schedule, and at the end of each day, I review my calendar to check what I’ve completed and what needs rescheduling. However, I’ve noticed that while future events sync perfectly, past events (including today’s and yesterday’s) are not syncing to my Google calendar. This makes it harder for me to track what has been accomplished or adjust plans.

I’m also planning to migrate to the new generation (NG) sync flow you’ve developed. But before I do, I wanted to ask:
	•	Is it possible to configure the NG flow to include today’s and maybe even yesterday’s events in the sync?
	•	If so, do you have any guidance on how to set that up?
	•	Additionally, is there a way to achieve this with the older flow? If not, I’ll move to the NG flow, but it feels like a lot of setup work. I could be overthinking it, though!

Lastly, I’d appreciate any tips on hosting the files myself and getting the NG flow operational. Not using render.com, but I have my own VPS on Ubuntu. Hopefully you can give me some directions on this and which files I need. Only from the directory, calendar_sync_helper (https://github.com/MShekow/ng-outlook-google-calendar-sync/tree/main/calendar_sync_helper) or also the python files in the root? 

Thanks again for your work, and I look forward to your insights!

**Comment by Tosko4** [comment]
Hey @MShekow,

I've just set up a Docker container for your project, and I wanted to walk you through what I did. This might also serve as a basis for a manual or documentation if needed. Everything seems to work, although I encountered a specific error in the logs that I could use your insight on.

### Steps I Took

1. **Environment Setup**:  
   I’m running this on a VPS with Linux.

2. **Cloning the Repository**:
   ```
   git clone https://github.com/MShekow/ng-outlook-google-calendar-sync.git
   cd ng-outlook-google-calendar-sync
   ```

3. **Creating Docker Configuration**:
   I added two files in the project directory: `Dockerfile` and `docker-compose.yml`.

   **Dockerfile**:
   ```Dockerfile
   # Use a lightweight Python base image with a specific version
   FROM python:3.12.7-slim

   # Set environment variables for Python and Poetry
   ENV PYTHON_VERSION=3.12.7 \
       POETRY_VERSION=1.8.4 \
       POETRY_VIRTUALENVS_CREATE=false \
       PATH="/root/.local/bin:$PATH"

   # Set the working directory in the container
   WORKDIR /app

   # Install system dependencies
   RUN apt-get update && apt-get install -y curl && \
       apt-get clean && rm -rf /var/lib/apt/lists/*

   # Install Poetry
   RUN curl -sSL https://install.python-poetry.org | python3 -

   # Copy the project files into the container
   COPY . .

   # Install Python dependencies using Poetry
   RUN poetry install

   # Expose port 8000 (FastAPI default)
   EXPOSE 8000

   # Command to start the FastAPI app
   CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
   ```

   **docker-compose.yml**:
   ```yaml
   version: '3.8'

   services:
     sync-helper:
       build: .
       container_name: sync-helper
       ports:
         - "8000:8000"  # Map container's port 8000 to host's port 8000
       restart: unless-stopped
       environment:
         PYTHON_VERSION: "3.12.7"
         POETRY_VERSION: "1.8.4"
   ```

4. **Building and Running the Container**:
   I ran the following commands:
   ```sh
   docker-compose build
   docker-compose up -d
   ```

   This successfully created a Docker container with port 8000 exposed.

### Issue Observed

Upon checking the logs, I noticed the following:

1. `POST /extract-events HTTP/1.1" 200 OK`
2. `GET //_api/SP.APIHubConnector.InvokeQuery HTTP/1.1" 404 Not Found`

It seems like the script works fine overall, but I'm getting these `404` errors repeatedly. Specifically, the `GET` request for `/_api/SP.APIHubConnector.InvokeQuery` seems to be failing. I’m not sure if this is something critical or just a benign issue.

### Questions

- Do you have any insights on why the `404 Not Found` might be happening with that `GET` request?
- Is it expected behavior in this context, or am I missing a configuration step somewhere?

I'd appreciate your thoughts on this, and if you have suggestions on what to adjust, I'm all ears. Maybe we can collaborate to iron this out for a smoother container experience.

Thanks in advance for your help! 😊

**Comment by Tosko4** [comment]
Hi once more... sorry for the spam.

I’ve been working with your repository and as mentioned I need to sync events from a certain number of days in the past. To achieve this, I’ve set up an integer variable `pastDays` in my environment. I tried to change the Start Time to use those values, which did not work. 

Currently, the `filter_outdated_events` function in `utils.py` filters events starting from the current UTC time (`utcNow()`), which doesn't include past events. I'd like to suggest a modification that allows the function to include events from `pastDays` days ago up to now.

To achieve this, I've set up an integer variable `pastDays` in my environment, where `pastDays` is a **positive integer** (e.g., `2` to include events from 2 days ago).

### **Suggested Changes:**

1. **Modify the `filter_outdated_events` Function:**

   Update the function to accept a `past_days` parameter (a positive integer) and adjust the `now` variable by subtracting `past_days` days from the current UTC time:

   ```python
   from datetime import timedelta

   def filter_outdated_events(input_data: ComputeActionsInput, past_days: int):
       now = get_current_utc_date() - timedelta(days=past_days)

       input_data.cal1events = [
           e for e in input_data.cal1events
           if AbstractCalendarEvent.from_implementation(e).start >= now
       ]
       input_data.cal2events = [
           e for e in input_data.cal2events
           if e.start >= now
       ]
   ```

2. **Pass the `pastDays` Variable When Calling the Function:**

   ```python
   filter_outdated_events(input_data, pastDays)
   ```

### **Notes:**

- I haven't had time to test this thoroughly or check for all possible edge cases.
- Since you're more familiar with the codebase, you might be aware of additional areas that require adjustment to accommodate this change.
- I hope this suggestion provides a helpful starting point for implementing this functionality.

Thank you for your hard work on this project—it's been incredibly valuable thusfar!

**Comment by MShekow** [comment]
Hey @Tosko4, I'm glad that the project is useful to you.

It's always nice to see that most of the reported issues are are "edge use cases" (meaning that the tool mostly works as intended). Your case is also an edge case, but I think I can support it without too much effort. ;)

So here are few remarks, I hope I've addressed all your points (if not, please just ask again):

- To **self-host** the sync helper service, Docker is a great idea. I have deep knowledge in writing Dockerfiles, and I'll create one, together with a compose.yml, and some basic instructions on how to get it running. Thanks for already providing a suggestion, which I'll base my Dockerfile on.
- It is expected behavior that you see these `GET //_api/SP.APIHubConnector.InvokeQuery HTTP/1.1" 404 Not Found` calls in your server logs. In Power Automate (PA), I'm using a SharePoint HTTP action, only because it is "free" (non-premium), not because I want to. The disadvantage of that action is that expects to talk to a (real) SharePoint service, and I suppose that SharePoint does have this `/_api/SP.APIHubConnector.InvokeQuery` endpoint. In any case, the PA SharePoint action succeeds, even though our HTTP service returns `404` for that endpoint 🤷 
- To sync days in the past, you'll need to locate the actions titled `Get [Outlook|Google] calendar view of events ...` and change the _expression_ code in the _start time_ field from `utcNow()` to `addHours(utcNow(),-8)` (replacing the `8` with any number you desire)
- As you correctly observed, the sync helper service filters out all _past_ events from the two incoming calendar data streams. The rationale for this is explained [here](https://github.com/MShekow/ng-outlook-google-calendar-sync/blob/main/implementation-notes.md#algorithm-decisions). I decided to so for precautionary measures, but it is really only needed when the two calendar streams were retrieved at (significantly) different points of time (which is only the case when using the _mirror file_ feature). In normal cases, it's not needed. Anyways, to make your use case work, I'm going to add another header field that simply disables this filtering process. I'll let you know once I've done so, and what the header's name is, so you can simply add it to your `Compute calendar modification actions` action.
- Unless several other people ask about synchronizing past events, I'll not build a new version of the PA flow zip file, but instead expect that people make these small modifications to their PA flow themselves (in summary: adding the header to the `Compute calendar modification actions` action, and changing the _start time_ in the 2 used `Get [Outlook|Google] calendar view of events ...` actions)

**Comment by Tosko4** [comment]
Hey @MShekow , thank you for getting back to me and for clarifying everything so thoroughly!

It’s again an amazing project and works well, and that my situation is more of an edge case I can also understand. I **really** appreciate your willingness to address it nonetheless—it definitely helps me keep everything organized on my end without too much hassle. 😅

#Remarks on Your Updates:

	1.	**Docker Support:**
Awesome that you’re considering adding an official Dockerfile and compose setup based on what I shared! That’ll be super helpful for anyone else looking to self-host—glad my suggestion could contribute to making that happen. I’m really looking forward to seeing what you come up with. And maybe learn a thing or two on what I've missed. 

	2.	**404 Not Found Logs:**
Thanks for explaining the origin of the 404 error related to the SharePoint HTTP action. Your choice to use the non-premium action makes a lot of sense, even if it comes with some quirks. Now that I understand it’s expected behavior, I’ll just ignore those messages in the logs and move on. 🤷‍♂️

	3.	**Syncing Past Events:**
Thanks for pointing out where I can change the expressions to sync past events! I’ll definitely give it a try by updating the start time expression in the `Get [Outlook|Google]` calendar view of events actions. And it’s fantastic that you’re adding a header field to disable the filtering process—that should make things even smoother for edge cases like mine.

I completely understand that adding past-event support to the official PA flow might not be worth it unless there’s broader demand. For now, I’m comfortable making these manual tweaks myself, especially with your clear instructions to come.

Thanks again for being so open to collaboration and for the detailed response. Let me know if I can help test anything or provide more feedback—I’m more than happy to assist! 😊

**Comment by MShekow** [comment]
@Tosko4 you're welcome. I've made the changes, see https://github.com/MShekow/ng-outlook-google-calendar-sync/commit/b1e0a2e1ce4e045593fe9ee58586d1779d83fb02 and https://github.com/MShekow/ng-outlook-google-calendar-sync/commit/ac421f717e856182a9a91bc8936f46948d33e48f

I've also deployed the changes to https://ng-outlook-google-calendar-sync.onrender.com

The new header is called `X-Disable-Past-Event-Filter`, just set it to `true` in Power Automate.

**Comment by cyrduf** [comment]
Hello **@MShekow, @Tosko4** ,

I'm also discover the NG sync and it's clearly a good tool based on PA :) I use NG Outlook Google calendar sync v0.2 the new version, and I have discussed about similar subjects for past events and some other minor points.

I use NG flow to bidirectional sync. and I only test without any encryption or security from now. But I expect to test/use encryption or SSL later.

My questions here, as you work actively on this NG tools:

- I see there is now option for past events in _https://ng-outlook-google-calendar-sync.onrender.com_, but as I not live in US, what is the best : install and self-host the sync helper service on my server ? or continue to use this one ?
- If I want to self-host: I have an AlmaLinux VPS for my website, with ability to add small applications, is it the actual configuration (docker, ....) usable to install this on my VPS ? 
- **@Tosko4** : have you encountered some problems with you own server or can I follow readme's to start also my own instance ? Last point, your problem _"GET //api/SP.APIHubConnector.InvokeQuery HTTP/1.1" 404 Not Found"_ is it linked with the self-host install or not ?
- In this way I will be comfortable to test each of the 2 options for managing past dates... but I don't measure the complexity of the work (and also security tips if I self host the sync helper if it's on server)

- I also expect at the end to configure SSL transfers between the sync helper server and the PA flow (for security) : is it possible with actual NG PA flow and the render.com helper.

Thank you for your helps.
Regards

**Comment by MShekow** [comment]
@Tosko4 for the header's _value_, you should omit the double quotes and just write `true` instead of `"true"`.

If that doesn't fix it, then you might need to take a closer look at the _output_ of the `Get [Outlook|Google] calendar view of events ...` actions: does the output properly include the requested past events?

**Comment by Tosko4** [comment]
When I enter `true` and save the flow in MS Power Automate, it automatically adds double quotes around `true`, preventing me from testing it effectively.

Additionally, when I inspect the body of the "Get Google Calendar Items" action, I can see entries with start dates like: `"start": "2024-11-19T08:30:00+00:00"`. 

This indicates that the flow is retrieving the data correctly, but there seems to be an issue with how the data is being processed further down the flow.

**Comment by MShekow** [comment]
I've run my sync helper service in a debugger and determined that the double quotes are _not_ the root cause of the problem.

In your case I'm afraid we have to take out the "big guns": if you're willing to send me the _Inputs_ of the `Compute calendar modification actions` action (which contains _sensitive data_ of your calendar events!), and send it as file to info@augmentedmind.de, I'd be willing to debug the problem. Make sure to also send me the timestamp of when the flow ran.

If that's not an option, you'll have to debug the Python code yourself.

**Comment by Tosko4** [comment]
Pulling out the "big guns" to troubleshoot this is always a relief. I want to sincerely thank you for your help. To minimize unnecessary clutter in the parameters/body, I've isolated a single event from my Google Calendar. This event is from the past and hasn’t synced to my Outlook calendar. While I don’t think the issue is with formatting—since future events sync correctly—it’s possible I’m overlooking something or jumping to conclusions too fast. Will this do?

```json
{
  "dataset": "http://<domain>:8000",
  "parameters/method": "POST",
  "parameters/uri": "/compute-actions",
  "parameters/headers": {
    "X-Unique-Sync-Prefix": "syncer",
    "X-SyncBlocker-Title-Prefix": "",
    "X-Anonymized-Title-Placeholder": "",
    "X-Ignore-Description-Equality-Check": "False",
    "X-Disable-Past-Event-Filter": "true"
  },
  "parameters/body": "{\"cal1events\": [{\"sync_correlation_id\":\"1jv3lbeqnht2mo1cbq9aomp9oi\",\"title\":\"Test Google Event\",\"description\":\"\",\"location\":\"\",\"start\":\"2024-11-22T06:00:00Z\",\"end\":\"2024-11-22T07:00:00Z\",\"is_all_day\":false,\"attendees\":null,\"show_as\":null,\"sensitivity\":null}]}"
}

**Comment by MShekow** [comment]
This snippet can't possibly be a valid body. The `cal2events` is missing entirely (it is a _required_ input). I really do need the **entire** body. The devil is always in the details.

**Comment by Tosko4** [comment]
@MShekow , sorry it took a bit to respond. But I have just sent you an email with subject Parameters wich the json export you requested. I have also added screenshots of the start time of the 4 calendar actions in the flow and one from the computer-actions so you can cross check with there.

Thanks in advance my friend!

**Comment by Tosko4** [comment]
The issue I run into is that events in the past are not created in Outlook, while they are in Google. I think I did double check if there were start and end dates in the json file, prior to the day this flow was executed. I grabbed the very first flow after cleaning everything up in both calendars and yet, only future events sync.

I don't want to burn a lot of your time though. But have you managed to get past events sync from Google to Outlook? If so, then the code is correct and I might be doing something wrong. I could create the flow from scratch again.

**Comment by MShekow** [comment]
In this case, your anonymization process is making it impossible to diagnose the problem. In the 81 to-be-created events, the first ones are _past_ events (from Nov. 19th).

There is no special if-else logic in the code that would do things differently, depending on whether cal1events or cal2events data is from Outlook or Google.

And yes, I tested it just now, it works just fine.
![{666CA462-AD3B-4E49-B083-E90E009A94AA}](https://github.com/user-attachments/assets/84c2ff06-599f-466c-835d-4b480a4a8485)
![{209204DB-15DD-469E-A47F-78DC59EA340B}](https://github.com/user-attachments/assets/ff34aee0-39bc-44cf-8738-26b4dd1dee4f)

**Comment by Tosko4** [comment]
I’ve resolved the issue on my end. As mentioned in another thread, I customized your flow to better align with my toolset. However, I realized I made an error in my thought process and mistakenly believed I was on the right track. That’s now been corrected, so I’ll go ahead and close this issue.
