### ISSUE TITLE
Performance Discrepancy in Bi-Directional Sync: Google to Outlook vs Outlook to Google

### ISSUE THREAD

**Issue by Tosko4** [MShekow/ng-outlook-google-calendar-sync#13]
Hi @MShekow ,

I've set up two flows for bi-directional synchronization between Google Calendar and Outlook Calendar: 

1. **Outlook to Google**  
2. **Google to Outlook**

While the setup works as intended, I've noticed a significant performance difference between the two flows:

- **Outlook to Google**: Average runtime is **15 seconds**.
![image](https://github.com/user-attachments/assets/62f5a06a-4345-44ca-a22b-a6e761828da7)

- **Google to Outlook**: Average runtime is **1:31 minutes**.
![image](https://github.com/user-attachments/assets/f553c926-4835-40b7-9387-d40c6a4ef58d)

### Observations

- Both flows use the same NG logic for synchronization.
- The delay in the **Google to Outlook** flow occurs consistently, regardless of the number of events being synchronized or the specific conditions applied.

### Question

Do you have any idea why the **Google to Outlook** flow takes so much longer to execute compared to the **Outlook to Google** flow? Is there something about the API, throttling, or potential processing differences between the platforms that could explain this discrepancy?

Looking forward to your insights!

**Comment by MShekow** [comment]
Well, just looking at the total duration won't allow you to diagnose the problem. Just open one of the _runs_ and look at the durations of the individual PA actions to find out what part of the flow is slow.

**Comment by Tosko4** [comment]
I added an extra condition check before creating or updating events. However, I noticed it runs through 73 loops, taking about 0.8–0.9 seconds per loop. This explains why it’s slower compared to the Outlook-to-Google sync. Initially, syncing from Outlook to Google took 1:20 minutes for 84 events. The Outlook-to-Google process seems more efficient, as it only needs 1–6 loops, whereas the Google-to-Outlook process repeatedly goes through 70–80 loops.

![image](https://github.com/user-attachments/assets/61d6c354-9c48-40bb-8f66-40c2527cf2d0)
![image](https://github.com/user-attachments/assets/b63a8abb-1440-4edb-b52d-d5ce1448e259)

**Comment by MShekow** [comment]
In this case, the most likely reason is that Outlook is retroactively _changing_ the _description_ of the event.

Example: a Google event has a description: `<html><body>Some description</body></html>`, the flow syncs this description to Outlook, but then the Outlook platform changes the description internally to `<html><head></head><body>Some description</body></html>`.

The only workaround is to set the `Setting: ignore description comparison` to `true`. However, you'll have to live with the fact that _real_ updates that are made to the Google events _after_ they have been synchronized will no longer be synced to Outlook.

Believe me, I've tried to make this work in a better way, e.g. by parsing the HTML, converting it to text, and comparing it, but there were more and more edge cases which I couldn't solve, so I gave up and built this simplified solution.

**Comment by Tosko4** [comment]
Thank you for the detailed explanation, your approach makes a lot of sense, especially given how tricky it can be to account for all the platform-induced quirks with descriptions. I completely understand why you opted for a simplified solution after encountering so many edge cases.

That said, your response got me thinking though, and I wanted to run an idea by you to see if this was something you’ve already tested before I end up going down another rabbit hole myself.

The idea is to implement a lightweight description normalization process rather than full HTML parsing. This would involve:

1.	Cleanup simple expressions to strip redundant tags (like <head>, <body> or inline styles) without diving into deeper HTML structures.
2.	For cases where the HTML differs but the core content is the same, flattening the description to plain text for a more straightforward comparison.
3.	Generating a hash of the cleaned description for both Google and Outlook events and only syncing when the hashes differ.

I realize this approach still comes with challenges, and you may have already explored something similar. But if this idea wasn’t tested, I thought it might offer a middle ground to reduce unnecessary loops without abandoning description updates entirely.

I’d love to hear your thoughts on whether this might be worth exploring further or if it’s likely to hit the same roadblocks you’ve already encountered.

**Comment by MShekow** [comment]
You'd have to think about where to store the hash, so that's one problem. And the other problem, simply put: "concept sounds easy on paper, extremely hard in practice". For instance, just throwing away HTML tags is not an option, you'll have newline and spacing issues.

I won't go into that rabbit hole again, I've just burned too much time in that already. You can always implement your own solution.

**Comment by Tosko4** [comment]
I can accept the duration time. It's not like we're talking about a lot. Was just curious, let's close this "issue" 😀
